# https://docs.expo.dev/build/building-on-ci/#github-actions
name: EAS Development Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: bun install
      - name: Build for simulators and Android device on EAS
        run: eas build --profile development --platform all --non-interactive --no-wait
      - name: Build for iOS on-device development on EAS
        run: eas build --profile development:device --platform ios --non-interactive --no-wait
